spring:
  application:
    name: store
stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  timeout: 2000
  supported-currencies: USD, GBP, EUR
payment-Gateway: paypal #,stripe
mail:
  host: https://smtp.gmail.com
  port: 5761